### ISSUE TITLE
WebGL version has bugs

### ISSUE THREAD

**Issue by livingcreative** [gammaker/flying-particles#1]
It's not possible to create issues for web version (located here: https://github.com/gammaker/gammaker.github.io/tree/master/particles)

There's a bug in `RenderFrame()` function inside `for` loop through `numBatches`. Within last iteration `particleCount` gets negative value which results in `drawArrays` call error (GL_INVALID_VALUE generated every frame).

**Comment by devoln** [comment]
Thank you. I fixed it.
